# Generated by Django 3.0.4 on 2020-03-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('guests', models.IntegerField(default=0)),
                ('selected_meats', models.ManyToManyField(to='planner.Meat')),
            ],
        ),
        migrations.CreateModel(
            name='BBQEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('share_link', models.CharField(max_length=200)),
                ('available_meat', models.ManyToManyField(to='planner.Meat')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Organizer')),
            ],
        ),
    ]
