# Generated by Django 3.0.4 on 2020-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meat',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
