# Generated by Django 3.0.4 on 2020-03-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_bbqevent_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='selected_meats',
        ),
        migrations.CreateModel(
            name='MeatReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('meat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.Meat')),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='meat_reservations',
            field=models.ManyToManyField(to='planner.MeatReservation'),
        ),
    ]
