# Generated by Django 3.0.4 on 2020-03-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20200314_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatreservation',
            name='meat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Meat'),
        ),
    ]
